name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps: 
      - name: Build docs
        run: |
          cd docs
          yarn install
          yarn docs:build

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
            branch: gh-pages
            folder: docs/.vuepress/dist
            target-folder: docs
