name: Node CI

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Build docs
        run: |
          cd docs
          yarn install
          yarn docs:build
    
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
            branch: gh-pages
            folder: docs/.vuepress/dist
            target-folder: docs
